### ISSUE TITLE
Doesn't appear to do anything

### ISSUE THREAD

**Issue by chefhoobajoob** [florianb/atom-gradle-ci#13]
I have version 1.2.3 of Atom, installed language-groovy and gradle-ci.

After loading a project folder that contains build.gradle, gradle.properties, gradlew, and gradlew.bat, I can see a "Gradle 2.8" status item in the lower right hand corner.

If I hover over that version number, I get a little popup that says "You don't have any builds yet".

If I right-click on the version number, I get a context menu named "GradleCI" with the submenu items "toggle results" and "invoke build".

If I click on "invoke build", nothing happens. I don't understand how it could if I haven't told it what gradle tasks I want it to run in the first place.

**Comment by chefhoobajoob** [comment]
Ah - found the little video instruction thing on the repository page.

So, how do I configure what gradle tasks I want it to run? Does it only run the 'build' task?

**Comment by florianb** [comment]
Hi @chefhoobajoob - thanks for asking.

There's a setting "Task/s to run with Gradle" in the package-settings. It defaults to "clean test". But you are free to define any other tasks or even command-line options since the whole test gets appended to the gradle-cli.
