### ISSUE TITLE
Uncaught ReferenceError: item is not defined

### ISSUE THREAD

**Issue by annahosanna** [florianb/atom-gradle-ci#4]
[Enter steps to reproduce below:]
This was immediately preceded by the error message from issue 6804. The steps to reproduce are: The error initially occurred while viewing the results of a gradle build _while_ it was being redirected to a file (gradle --stacktrace -d compileTestJava > out.txt 2>&1), but continued after out.txt was closed.   Only the build.gradle and out.txt file were open when there error started. The error seemed to occur after a fixed period of time rather than any user interaction.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [gradle-ci](https://github.com/florianb/atom-gradle-ci) package, v0.2.3
### Stack Trace

Uncaught ReferenceError: item is not defined

```
At C:\Users\agilex01\.atom\packages\gradle-ci\node_modules\chokidar\index.js:261

ReferenceError: item is not defined
    at EventEmitter.FSWatcher._emitError (C:\Users\agilex01\.atom\packages\gradle-ci\node_modules\chokidar\index.js:261:15)
    at C:\Users\agilex01\.atom\packages\gradle-ci\node_modules\chokidar\index.js:298:39
    at FSReqWrap.oncomplete (fs.js:77:15)
```
### Commands

```
     -3:46.6.0 core:move-left (atom-text-editor.editor.is-focused)
 37x -3:46.1.0 core:move-down (atom-text-editor.editor.is-focused)
 19x -3:44.3.0 core:move-up (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
gradle-ci, v0.2.3
language-gradle, v0.0.3
language-groovy, v0.3.0

# Dev
No dev packages
```

**Comment by florianb** [comment]
@annahosanna: Thanks for reporting. I'm currently rewriting the package for Atom 1.x - after tat i'll examine your reported issue. I'm sorry for any inconveniences.

**Comment by florianb** [comment]
This issue has been fixed. But please be patient, i'm still working on a 1.x-release which will change the build-invokation.
