### ISSUE TITLE
Causes Atom to become unusable

### ISSUE THREAD

**Issue by lwis** [florianb/atom-gradle-ci#5]
Latest Atom/latest plugin release/Gradle 2.4 causes Atom to become unusably slow.

**Comment by florianb** [comment]
@lwis: Thanks for reporting. I'm currently porting the package to Atom 1.x - i'll take a look on the performance. Sorry for answering that late.

**Comment by florianb** [comment]
@lwis - i recently published version 1.0.0 of the package. I rewrote a lot of the business logic behind the curtain, i really hope this solves your experienced performance problems. I'd like to close the issue as long as you don't report anything else.
