### ISSUE TITLE
How do I install GradleCI

### ISSUE THREAD

**Issue by stewartbryson** [florianb/atom-gradle-ci#7]
I've only installed packages in Atom using the GUI... I'm not sure how to get this installed.

Thanks.

**Comment by florianb** [comment]
@stewartbryson: Thanks for reporting. I'm working on a fix - I am sorry for any inconvenience.

**Comment by florianb** [comment]
The Package is now 1.x compliant and installable. But please be patient, i'm still working on a 1.x-release which will change the build-invokation.
